### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by coupal** [integraleets/integrale.etsmtl.ca#2]
- [ ] Config dev + prod
- [ ] Deploy on server
- [x] Separate with  section of code
- [ ] Login_required after login in should bring back to request page
- [ ] Account admin
- [ ] Make everything pretty
  - [x] Footer
  - [ ] News
  - [x] Addentry
  - [x] Login
  - [x] Signup
  - [x] Contact
  - [ ] Profile
- [x] Menu mobile est affreux
- [ ] Bouton mauve
- [ ] Edit news and see news individuals
- [ ] Recaptcha for signup / contact
